services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=testdb
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - .:/app
    command: /bin/sh -c "until nc -z rabbitmq 5672; do echo 'Esperando a desgraça do RabbitMQ...'; sleep 2; done; node app/app.js"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"